 
spring:
  profiles:
    active: peer1

server: 
  servlet:
    context-path: /spring-cloud-eureka    

eureka: 
  client:
    service-url:
      # 对等实例的地址 (可以提取出来作为公共部分)
      defaultZone: http://127.0.0.1:6868/eureka/
    # 健康检查
    healthcheck:
      enabled: true
  server:
    enable-self-preservation: false
    # 回收时间间隔
    eviction-interval-timer-in-ms: 6000

# 通过不同的profiles，实现eureka对等实例
---
spring:
  profiles: peer1

  application:
    name: spring-cloud-eureka 
    
server:
  port: 6868
 
eureka:
  instance:
    hostname: 127.0.0.1

---
spring:
  profiles: peer2
  application:
    name: spring-cloud-eureka-replica

server:
  port: 6869

eureka:
  instance:
    hostname: 127.0.0.1




