
server:
  port: 6868
 
  servlet:
    context-path: /spring-cloud-eureka
 
spring:
  profiles:
    active:
    - dev
  application:
    name: spring-cloud-eureka
  autoconfigure:
    exclude:
    - 

eureka:
  client:
   # 自身不注册
    register-with-eureka: false
    fetch-registry: false

  instance:
    instance-id: ${spring.application.name}:${server.port}
    ip-address: 127.0.0.1
  server:
    enable-self-preservation: false
    # 回收时间间隔
    eviction-interval-timer-in-ms: 6000
    

  http:
    log-request-details: true

# spring.devtools.restart.enabled 禁用devtools自动重启功能，直接用IDE的热部署
  devtools:
    restart:
      enabled: true
      additional-paths:
      - src/main/java

   










