
server:
  port: 7070
 
  servlet:
    context-path: /
 
spring:
  application:
    name: spring-cloud-ribbon
  profiles:
    active:
    - dev
  autoconfigure:
    exclude:
    - 

  http:
    log-request-details: true

# spring.devtools.restart.enabled 禁用devtools自动重启功能，直接用IDE的热部署
  devtools:
    restart:
      enabled: true
      additional-paths:
      - src/main/java
      



ribbon:
  eager-load:
    # 允许负荷缓存
    enabled: true

# 注册中心
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    registry-fetch-interval-seconds: 5    
    service-url: 
      #defaultZone: http://192.168.5.11:6868/eureka/,http://192.168.5.12:6869/eureka/
      defaultZone: http://192.168.5.11:6868/eureka/







