
server:
 port: 6868 	# 服务端口

spring:
 application:
  name: spring-cloud-eureka # 应用名称

eureka:
 client:
  registerWithEureka: true 	# 是否注册到Eureka注册中心
  fetchRegistry: true # 是否从Eureka获取注册信息
  serviceUrl:
   defaultZone: http://localhost:6869/${spring.application.name}
 instance:
  prefer-ip-address: true # 是否将自身ip注册到Eureka
  ip-address: 127.0.0.1
  instance-id: ${spring.application.name}:${server.port} # 实例id
 server:
 enable-self-preservation: false # 是否开启自我保护模式
 eviction-interval-timer-in-ms: 6000 # 清理间隔
