
server:
  port: 7070
 
  servlet:
    context-path: /
 
spring:
  profiles:
    active: dev
    
  application:
    name: 
  autoconfigure:
    exclude:
    - 

  http:
    log-request-details: true

# spring.devtools.restart.enabled 禁用devtools自动重启功能，直接用IDE的热部署
  devtools:
    restart:
      enabled: true
      additional-paths:
      - src/main/java

# 注册中心
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5    
    service-url: 
      #defaultZone: http://192.168.5.11:6868/eureka/,http://192.168.5.12:6869/eureka/
      defaultZone: http://192.168.5.11:6868/eureka/

feign:
  client: 
    # false表示优先级较高为@Configuration
    default-to-properties: false
    config: 
     # 所有客户端默认的属性
      default: 
        connect-timeout: 3000
        read-timeout: 3000
        logger-level: basic
      # 特定客户端的属性
      users: 
        connect-timeout: 5000
        read-timeout: 5000
        decode404: false
  # 开启okhttp      
  okhttp:
      enabled: true
  # 请求/响应开启GZIP压缩
  compression:
    request:
      enabled: true
      # 要压缩的媒体类型
      mime-types: text/xml,application/xml,application/json
      # 最小请求阈值长度
      min-request-size: 2048
    response:
      enabled: true
  hystrix:
    # 是否启用hystrix，启用hystrix之后Feign调用超时 
    # timed-out and no fallback available. 原因暂时不明确
    enabled: true
  
ribbon:
  eureka:
    enabled: true

uni: 
  user:
    api:  
      url: http://172.25.62.77:9090/hotel-manage-platform-api