
server:
  port: 2020
 
  servlet:
    context-path: /
 
spring:
  profiles:
    active:
    - dev

  # 应用名称，注册到eureka显示的名称
  application:
    name: spring-cloud-consumer

  autoconfigure:
    exclude:
    - 

  cloud:
    loadbalancer:
      retry:
        # 负载均衡重试
        enabled: true
    # 兼容性检查，通常在架构初期打开，后面关闭
    compatibility-verifier:
      enabled: true
      
  http:
    log-request-details: true

# spring.devtools.restart.enabled 禁用devtools自动重启功能，直接用IDE的热部署
  devtools:
    restart:
      enabled: true
      additional-paths:
      - src/main/java
  aop:
    proxy-target-class: true

# 注册中心
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    registry-fetch-interval-seconds: 5    
    service-url: 
      #defaultZone: http://192.168.5.11:6868/eureka/,http://192.168.5.12:6869/eureka/
      defaultZone: http://192.168.5.11:6868/eureka/
      
  instance:
    instance-id: ${spring.application.name}:${server.port}
    #lease-renewal-interval-in-seconds: 5









