
server:
  port: 7070
 
  servlet:
    context-path: /
 
spring:
  profiles:
    active: dev
    
  application:
    name: 
  autoconfigure:
    exclude:
    - 

  cloud:
    config:
      # 配置中心服务，配置中心(Cloud Config Server)也是一个服务
      uri:
      - http://myconfigserver.com

  http:
    log-request-details: true

# spring.devtools.restart.enabled 禁用devtools自动重启功能，直接用IDE的热部署
  devtools:
    restart:
      enabled: true
      additional-paths:
      - src/main/java












