
server:
  port: 7070
 
  servlet:
    context-path: /

spring:
  profiles:
    active: dev
    
  application:
    name: spring-cloud-test
  autoconfigure:
    exclude:
    - 
  cloud: 
    util:
      enabled: true
    config: 
     # 覆盖本地属性源
      override-none: true
      # 系统属性(系统属性，命令行参数和环境变量)不能被远程覆盖
      override-system-properties: false
  http:
    log-request-details: true

# spring.devtools.restart.enabled 禁用devtools自动重启功能，直接用IDE的热部署
  devtools:
    restart:
      enabled: true
      additional-paths:
      - src/main/java












