
server:
  port: 7070
 
  servlet:
    context-path: /
 
spring:
  profiles:
    active: dev
    
  application:
    name: spring-cloud-function
  autoconfigure:
    exclude:
    - 

  http:
    log-request-details: true

# spring.devtools.restart.enabled 禁用devtools自动重启功能，直接用IDE的热部署
  devtools:
    restart:
      enabled: true
      additional-paths:
      - src/main/java

management:
  endpoints:
    web:
      exposure:
        exclude:
        - refresh
  endpoint:
    beans:
      enabled: true










