
server:
  port: 7070
  # 
  tomcat: 
    maxConnections: 4 # 最大连接数，超过了则拒绝连接
    
  servlet:
    context-path: /spring-cloud-provider
 
spring:
  profiles:
    active: dev
  
  # 应用名称，注册到eureka显示的名称
  application:
    name: spring-cloud-provider
    
  autoconfigure:
    exclude:
    - 

# spring.devtools.restart.enabled 禁用devtools自动重启功能，直接用IDE的热部署
  devtools:
    restart:
      enabled: false
      additional-paths:
      - src/main/java

# 注册中心
eureka:
  client:
    register-with-eureka: true # 是否注册到Eureka注册中心
    
    fetch-registry: true # 是否从Eureka获取注册信息
    registry-fetch-interval-seconds: 5
    service-url: 
      #defaultZone: http://127.0.0.1:6868/spring-cloud-eureka/eureka/
      #defaultZone: http://172.25.62.113:123456@peer2:8761/eureka/,http://172.25.62.183:6600/eureka/,http://172.25.62.184:6600/eureka/,http://172.25.62.185:6600/eureka/,http://172.25.62.50:7200/eureka/,http://172.25.102.121:8761/eureka/ 
      #defaultZone: http://172.25.102.121:8761/eureka/ 
      #defaultZone: http://172.25.62.50:7200/eureka/
      #defaultZone: http://192.168.5.1:6868/eureka/
      defaultZone: http://dev-registry.polyv.net:8760/eureka/
  #instance:
    #instance-id: ${spring.application.name}:${server.port}









