
server:
  port: 7070
 
#  servlet:
#    context-path: /spring-cloud-provider
 
spring:
  profiles:
    active: dev
  
  # 应用名称，注册到eureka显示的名称
  application:
    name: spring-cloud-provider
    
  autoconfigure:
    exclude:
    - 

  http:
    log-request-details: true

# spring.devtools.restart.enabled 禁用devtools自动重启功能，直接用IDE的热部署
  devtools:
    restart:
      enabled: true
      additional-paths:
      - src/main/java

# 注册中心
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: 
      #defaultZone: http://127.0.0.1:6868/spring-cloud-eureka/eureka/
      #defaultZone: http://172.25.62.113:123456@peer2:8761/eureka/,http://172.25.62.183:6600/eureka/,http://172.25.62.184:6600/eureka/,http://172.25.62.185:6600/eureka/,http://172.25.62.50:7200/eureka/,http://172.25.102.121:8761/eureka/ 
      #defaultZone: http://172.25.102.121:8761/eureka/ 
      defaultZone: http://172.25.62.50:7200/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}









